### ISSUE TITLE
Speaker data getting deleted once speakers add session info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-legacy#1] opened 2017-11-30 13:28 UTC
Once speakers add their session data most data of speakers is deleted.

* The first thought was:  
Currently all speakers need to confirm their email address before they can enter all their speaker data is during the sign up. 

Expected: Speaker can enter full information without having their email address confirmed.

**Comment by Anonymous26** [comment] 2017-11-30 14:03
I'm not able to reproduce this error. With an unverified account I'm able to submit speaker details in call for speakers section.

**Comment by mariobehling** [comment] 2017-11-30 14:56
You could be able to submit, but they don't seem to be stored.

Speaker data except very few fields arent saved on evetyay currently.

**Comment by SaptakS** [comment] 2017-12-01 05:16
@mariobehling I just tried with an unverified user and checked that all the data is being saved. Can you please give me an example of some user who faced this problem? That will really help in debugging. Thanks.

**Comment by mariobehling** [comment] 2017-12-01 10:38
@SaptakS 95% of speaker data (except name) on the FOSSASIA Summit live site are not being.

**Comment by mariobehling** [comment] 2017-12-01 10:39
I dont know what is the reason then.

**Comment by mariobehling** [comment] 2017-12-01 10:42
This is a message from a speaker:

> I  have submitted a proposal for this session - https://eventyay.com/events/mysessions/4328/
"Build your own Bitcoin Startup using Open-source Technology"
However, a technical bug in eventyay is preventing me from creating my speaker profile, can you help me

**Comment by mariobehling** [comment] 2017-12-01 10:47
The data is not there. Actually it should not be possible to submit a session event without adding the speaker details.

![screenshot from 2017-12-01 11-47-02](https://user-images.githubusercontent.com/1583873/33479432-613d59b0-d68d-11e7-9d87-cf074c425ada.png)

**Comment by mariobehling** [comment] 2017-12-01 10:57
Ok, you need to go through the whole process. 

The speaker data is getting deleted once speakers add their session information.

**Comment by SaptakS** [comment] 2017-12-01 11:01
@mariobehling true. That seems to be the problem. I will check and fix it ASAP.

**Comment by shubham-padia** [comment] 2017-12-01 11:35
@mariobehling @SaptakS from what i could figure out from the code only, the problem seems to be on L249 in https://github.com/fossasia/open-event-legacy/blob/development/app/helpers/data.py#L249 where save_speaker is called. 
What save_speaker does is it updates the info if speller from the request. 
As this function is called on create session, there is no speaker detail in the request and thus speaker detail is replaced with blank data.
I'd test and make a PR for this, but I'm on a train right now with no access to my laptop :(

**Comment by SaptakS** [comment] 2017-12-01 11:36
@shubham-padia problem solved. Pushing the code in some time.

**Comment by SaptakS** [comment] 2017-12-02 18:12
Has been fixed [here](https://github.com/fossasia/open-event-legacy/commit/a25855e4c8fec6165d72a831b8f70113cca108a6). Closing.

**Closed by SaptakS** 2017-12-02 18:12 UTC
Labels: bug, Priority:URGENT
